# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OidVMbeGgVZPjhE-k01ZhFnOvFb10kbM
"""

import math
class circle():
  pi = math.pi
  def __int__(self,r):
    self.rad = r
    print("circle created")
    def perim(self):
      return 2*pi*self.rad
      def area(self):
        return pi*self.rad*self.rad
        def __del__(self):
          print("circle deleted")
          return -1

class triangle():
  def __init__(self,a,b,c):
    self.z1 = a
    self.z2 = b
    self.z3 = c
    if(a+b>c and a+c>b and b+c>a):
      print(triangle is true)
    else:
      ptint ("triangle is false")
   def perim(self):
    return self.z1+self.z2+self.z3
    def area(self):
      s = (self.z1+self.z2+self.z3)/2
      retrn (s*(s_self.z1)*(s_self.z2)*(s_self.z3)**0/5)
      def is_triangle(self):
        if self.z1+self.z2>self.z3 and self.zz1+self.z3>self.z2 and self.z2+self.z3>self.z1
        return true
        else:
          return False
          def __del__(self):
            print("triangle deleted")

