# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhre7w2Bp10N4qK86XJsAEHFz9iEzAQ6
"""

def maximum3(a,b,c):
  a = max
  if b>max:
   max = b
  if c>max:
    max = c
    return max

def maximum100():
  a = input()
  a = int(a)
  max = a
  for i in range(99):
    a = int(input)
    if a>max:
      max = a
      return max

def mean():
  s = 0
  for i in range (100):
    s += int(input)
    return s/100.0

def inputlist():
  l = []
  k = 0
  while k != 5:
    k = int(input("please enter a number"))
    l.append(k)
    return l

def inputlist():
 l = []
 k = 0
 while 2>1:
  k = int(input())
  if k==5:
    break
    l.append(k)
    return l

def inputlist():
  def max_min(tr):
    tr.sort()
    return tr[-1],tr[0]
    A = inputlist()
    M,m = max-min(A)
    print(M,m)

def inputlist():
  l = []
  k = 0
  while k != 5:
    k = int(input("please enter a number"))
    l.append(k)
    return l
    def max_min(tr):
      tr.sort()
      return tr[-1],tr[0]
      tr.count()
      A = inputlist
      M,m = max_min(A)
      print(M,m)

