# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqPVDX_ag5l9_XZeFOlCfgOM_gP9HZah
"""

def rect(a,b):
  p = 2*(a+b)
  s = a*b
  print (p,s)
  return p,s
  K,M = t1,t2
  t1,t2 = 5

